In [2]:
import pandas as pd

In [ ]:
# Read the Traffic Dataset
traffic = pd.read_csv(r"C:\Users\ADMIN\Downloads\Integrated_Dataset_FINAL.csv")

In [ ]:

traffic

,DateTime,Junction,Vehicles,ID,date,hour,temperature_avg,humidity_avg,wind_speed,precipitation,event_flag,event_name
0,01-11-2015 00:00,1,15,20151101001,01-11-2015,0,29.5,42.2,8.7,10,1,Weekend
1,01-11-2015 01:00,1,13,20151101011,01-11-2015,1,29.5,42.2,8.7,10,1,Weekend
2,01-11-2015 02:00,1,10,20151101021,01-11-2015,2,29.5,42.2,8.7,10,1,Weekend
3,01-11-2015 03:00,1,7,20151101031,01-11-2015,3,29.5,42.2,8.7,10,1,Weekend
4,01-11-2015 04:00,1,9,20151101041,01-11-2015,4,29.5,42.2,8.7,10,1,Weekend
...,...,...,...,...,...,...,...,...,...,...,...,...
48115,30-06-2017 19:00,4,11,20170630194,30-06-2017,19,24.3,72.5,8.7,0,0,NaN
48116,30-06-2017 20:00,4,30,20170630204,30-06-2017,20,24.3,72.5,8.7,0,0,NaN
48117,30-06-2017 21:00,4,16,20170630214,30-06-2017,21,24.3,72.5,8.7,0,0,NaN
48118,30-06-2017 22:00,4,22,20170630224,30-06-2017,22,24.3,72.5,8.7,0,0,NaN
48119,30-06-2017 23:00,4,12,20170630234,30-06-2017,23,24.3,72.5,8.7,0,0,NaN

In [ ]:
# Check the null values and sum of those values in each column.
traffic.isna().sum()

DateTime               0
Junction               0
Vehicles               0
ID                     0
date                   0
hour                   0
temperature_avg        0
humidity_avg           0
wind_speed             0
precipitation          0
event_flag             0
event_name         33288
dtype: int64

In [ ]:
# If their is any null value fill those with None.
traffic['event_name'] = traffic['event_name'].fillna("None")

In [7]:
traffic.isna().sum()

DateTime           0
Junction           0
Vehicles           0
ID                 0
date               0
hour               0
temperature_avg    0
humidity_avg       0
wind_speed         0
precipitation      0
event_flag         0
event_name         0
dtype: int64

In [ ]:
# Drop duplicate values
traffic.drop_duplicates(inplace = True)

In [ ]:
#Convrt string date into date format
traffic['DateTime'] = pd.to_datetime(traffic['DateTime'], format="%d-%m-%Y %H:%M")

# Create date and hour column from Datetime
traffic['date'] = traffic['DateTime'].dt.date
traffic['hour'] = traffic['DateTime'].dt.hour

In [ ]:
#Read the data in dataframe.
traffic_hourly = traffic.groupby(['date', 'hour', 'Junction'])['Vehicles'].sum().reset_index()
traffic_hourly

             date  hour  Junction  Vehicles
0      2015-11-01     0         1        15
1      2015-11-01     0         2         6
2      2015-11-01     0         3         9
3      2015-11-01     1         1        13
4      2015-11-01     1         2         6
...           ...   ...       ...       ...
48115  2017-06-30    22         4        22
48116  2017-06-30    23         1        78
48117  2017-06-30    23         2        27
48118  2017-06-30    23         3        39
48119  2017-06-30    23         4        12

[48120 rows x 4 columns]

In [ ]:
# install scikit - learn
pip install scikit-learn
 
#Scikit-learn is a machine learning library in Python.
#It helps you build models, analyze data, and make predictions easily.

Requirement already satisfied: scikit-learn in c:\users\admin\appdata\local\programs\python\python314\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\admin\appdata\local\programs\python\python314\lib\site-packages (from scikit-learn) (2.3.4)
Requirement already satisfied: scipy>=1.10.0 in c:\users\admin\appdata\local\programs\python\python314\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.3.0 in c:\users\admin\appdata\local\programs\python\python314\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\admin\appdata\local\programs\python\python314\lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
# Apply StandardScaler to normalize the selected numerical columns.
# This helps improve model performance by ensuring all features have the same scale (mean=0, std=1).


from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
traffic[['Vehicles','temperature_avg','humidity_avg','wind_speed']] = scaler.fit_transform(
    traffic[['Vehicles','temperature_avg','humidity_avg','wind_speed']]
)

In [13]:
traffic

,DateTime,Junction,Vehicles,ID,date,hour,temperature_avg,humidity_avg,wind_speed,precipitation,event_flag,event_name
0,2015-11-01 00:00:00,1,-0.375489,20151101001,2015-11-01,0,0.531634,-1.861620,-0.711414,10,1,Weekend
1,2015-11-01 01:00:00,1,-0.471875,20151101011,2015-11-01,1,0.531634,-1.861620,-0.711414,10,1,Weekend
2,2015-11-01 02:00:00,1,-0.616454,20151101021,2015-11-01,2,0.531634,-1.861620,-0.711414,10,1,Weekend
3,2015-11-01 03:00:00,1,-0.761034,20151101031,2015-11-01,3,0.531634,-1.861620,-0.711414,10,1,Weekend
4,2015-11-01 04:00:00,1,-0.664648,20151101041,2015-11-01,4,0.531634,-1.861620,-0.711414,10,1,Weekend
...,...,...,...,...,...,...,...,...,...,...,...,...
48115,2017-06-30 19:00:00,4,-0.568261,20170630194,2017-06-30,19,-1.245023,1.166812,-0.711414,0,0,None
48116,2017-06-30 20:00:00,4,0.347408,20170630204,2017-06-30,20,-1.245023,1.166812,-0.711414,0,0,None
48117,2017-06-30 21:00:00,4,-0.327296,20170630214,2017-06-30,21,-1.245023,1.166812,-0.711414,0,0,None
48118,2017-06-30 22:00:00,4,-0.038137,20170630224,2017-06-30,22,-1.245023,1.166812,-0.711414,0,0,None
48119,2017-06-30 23:00:00,4,-0.520068,20170630234,2017-06-30,23,-1.245023,1.166812,-0.711414,0,0,None

In [ ]:
#Create hour, Day, month from Datetime.
traffic['hour'] = traffic['DateTime'].dt.hour

In [16]:
traffic['Day_of_Week'] = traffic['DateTime'].dt.dayofweek

In [18]:
traffic['month'] = traffic['DateTime'].dt.month

In [ ]:
 # Create a new column with previous hour's vehicle count

traffic['lag_1'] = traffic['Vehicles'].shift(1)

In [ ]:
# Create a new column with previous hour's vehicle count
traffic['lag_24'] = traffic['Vehicles'].shift(24)

In [ ]:
# Drop null values
traffic = traffic.dropna()

In [ ]:
# Create a binary indicator for weekends (Saturday=5, Sunday=6)
traffic.loc[:, 'is_weekend'] = (traffic['Day_of_Week'] >= 5).astype(int)

In [ ]:
# Create a binary indicator for special events (1 = event day, 0 = normal day)
traffic.loc[:, 'is_event'] = (traffic['event_flag'] == 1).astype(int)

In [ ]:
# Calculate correlation of all numeric features with the target variable 'Vehicles'
traffic.corr(numeric_only=True)['Vehicles']

Junction          -0.614320
Vehicles           1.000000
ID                 0.227774
hour               0.219938
temperature_avg    0.000020
humidity_avg      -0.003837
wind_speed        -0.009754
precipitation      0.005176
event_flag        -0.155758
Day_of_Week       -0.125773
month             -0.022420
lag_1              0.969982
lag_24             0.901522
is_weekend        -0.150304
is_event          -0.155758
Name: Vehicles, dtype: float64

In [ ]:
# Import Random Forest model for feature importance and train_test_split for splitting data into train and test sets
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

In [ ]:
# Select input features (X) and target variable (y) for the model

X = traffic[['hour','Day_of_Week','month','temperature_avg','humidity_avg',
             'wind_speed','is_weekend','is_event','lag_1','lag_24','Junction']]
y = traffic['Vehicles']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestRegressor()
model.fit(X_train, y_train)

RandomForestRegressor()

In [ ]:
# Retrieve and display the importance of each feature as learned by the Random Forest model

importance = pd.Series(model.feature_importances_, index=X.columns)
print(importance.sort_values(ascending=False))

lag_1              0.941470
lag_24             0.016759
hour               0.014733
humidity_avg       0.005705
wind_speed         0.005027
temperature_avg    0.004954
month              0.003773
Day_of_Week        0.003308
Junction           0.002929
is_event           0.000732
is_weekend         0.000610
dtype: float64